### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by piotr-gawron** [noyesno/awka#1]
I have a problem compiling your software.

Here is small info about my environment:
OS: ubuntu 16.04
gcc: 5.4.0

The summary of an error is like:
> make[1]: *** No rule to make target 'strfunc.o', needed by 'libawka.a'.  Stop.
> make[1]: Leaving directory '/home/gawi/Desktop/tmp/Martyn/awka/lib'
> Makefile:45: recipe for target 'libawka' failed
> make: *** [libawka] Error 2

In the attachment you can find output of `./configure` and `make` commands:
* [config-out.txt](https://github.com/noyesno/awka/files/1470898/config-out.txt)
* [make-out.txt](https://github.com/noyesno/awka/files/1470899/make-out.txt)

**Comment by drawkula** [comment]
I got the same problem with...
```
$ gcc -v |& tail -1
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
```
Commenting out `strfunc.o` in https://github.com/noyesno/awka/blob/d1c347902c4fc796895fda97862ff467477f906d/lib/Makefile.in#L34 before running `./configure ...` lets the build succeed but I've no idea what other side effects that may trigger...

More research is needed... ;-)

**Comment by rruggiero** [comment]
I have the same errors, did you ever find a reason for this?

**Comment by celem** [comment]
I have awka-0.7.5 working with no compile errors BUT it isn't from this repository. This repository does not match what I have (I'll show diffs below). I don't recall where I got mine but NOT from here. I recommend looking elsewhere for awka-0.7.5. Diffs below:
$ diff -rq awka awka-0.7.5
Files awka/awka/awka_exe.h and awka-0.7.5/awka/awka_exe.h differ
Files awka/awka/code.h and awka-0.7.5/awka/code.h differ
Files awka/awka/da.c and awka-0.7.5/awka/da.c differ
Files awka/awka/Makefile and awka-0.7.5/awka/Makefile differ
Files awka/awka/parse.c and awka-0.7.5/awka/parse.c differ
Files awka/awka/parse.h and awka-0.7.5/awka/parse.h differ
Files awka/awka/translate.c and awka-0.7.5/awka/translate.c differ
Files awka/config.cache and awka-0.7.5/config.cache differ
Files awka/config.h and awka-0.7.5/config.h differ
Files awka/config.log and awka-0.7.5/config.log differ
Files awka/config.status and awka-0.7.5/config.status differ
Only in awka-0.7.5: description-pak
Only in awka-0.7.5: doc-pak
Only in awka: elm-lib
Only in awka: .git
Files awka/lib/array.c and awka-0.7.5/lib/array.c differ
Files awka/lib/array.h and awka-0.7.5/lib/array.h differ
Files awka/lib/builtin.c and awka-0.7.5/lib/builtin.c differ
Files awka/lib/builtin.h and awka-0.7.5/lib/builtin.h differ
Files awka/lib/init.c and awka-0.7.5/lib/init.c differ
Files awka/lib/init.h and awka-0.7.5/lib/init.h differ
Files awka/lib/Makefile and awka-0.7.5/lib/Makefile differ
Files awka/lib/Makefile.in and awka-0.7.5/lib/Makefile.in differ
Files awka/Makefile and awka-0.7.5/Makefile differ
Files awka/regexp/regex.c and awka-0.7.5/regexp/regex.c differ
Only in awka: TODO

**Comment by drawkula** [comment]
Maybe [awka/0.7.5 from sourceforge.net](https://sourceforge.net/projects/gnuwin32/files/awka/0.7.5/)?

**Comment by celem** [comment]
I found where I got the source. Ignore this repository and get functional awka source from the home of awka:
[http://awka.sourceforge.net/index.html](url)

**Comment by noyesno** [comment]
The missing file is for glob match. It's missing by mistake.
Fixed by using "nstring.c"
