### ISSUE TITLE
inconsistency between awka and gawk for `==`

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [noyesno/awka#11]
See the difference below. I'd consider that this is a bug of awka that should be fixed.

```
$ awka '{ print $1 + 0 == $1 }' > a.c
$ gcc -lawka -o a.out a.c
$ builtin printf '%s\n'a | ./a.out
1
$ builtin printf '%s\n' .0 b c | gawk '{ print $1 + 0 == $1 }'
0
```

**Comment by jlp765** [comment]
fixed in #7

**Comment by prRZ5F4LXZ** [comment]
@jlp765 I don't see it being fixed.

```
awka=/tmp/github.com/jlp765/awka/awka/awka
tmpdir=$(mktemp -d)
"$awka" '{ print $1 + 0 == $1 }' > "$tmpdir"/a.c
gcc -lawka -o "$tmpdir"/a.out "$tmpdir"/a.c
builtin printf '%s\n' a | "$tmpdir"/a.out
1
builtin printf '%s\n' a | gawk '{ print $1 + 0 == $1 }'
0
```

**Comment by noyesno** [comment]
* `+` has higher precedence then `==`
* `"a" + 0 == "a"`   => `("a" + 0) == "a"`  =>  `0 == "a"` => `false` => `0`
* Thanks @jlp765 for the fixing to make it consistent with gawk.
* The real issue here is `"a" + 0` should trigger a runtime exception. - should enhance it in the future.

**Comment by prRZ5F4LXZ** [comment]
No. In gawk, "a", when used in the context of "a" + 0, is converted to 0.

https://www.gnu.org/software/gawk/manual/html_node/Strings-And-Numbers.html

**Comment by noyesno** [comment]
> No. In gawk, "a", when used in the context of "a" + 0, is converted to 0.
> 
> https://www.gnu.org/software/gawk/manual/html_node/Strings-And-Numbers.html

You are right. That's the behavior of gawk. My comment above is a note about the logic behind.
And @jlp765 have already fixed this issue in awka.

But to make things "correct", a runtime exception (warning) should be triggered at runtime. That will go further than gawk. Just leave a note here for future enhancement.
