### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by saltedcoffii** [noyesno/awka#5]
Please create a release of this so it can be distributed by packagers! Thank you

**Comment by drawkula** [comment]
You can package every daily git clone...
Where is the problem?

**Comment by saltedcoffii** [comment]
https://www.github.com/skycocker/chromebrew doesn't support git clones for stability's sake.

**Comment by drawkula** [comment]
And naming a random commit "release" to circumvent that would make it stable?
If your OS keeps you from using what you want to use, change your OS.
Or make an own clone and do own releases there.

**Comment by saltedcoffii** [comment]
I guess I was hoping the repo author would stabilize a commit and release it

**Comment by noyesno** [comment]
@saltedcoffii 
I created two release v0.7.5  and v0.7.6 using GitHub Releases/Tags. Not sure is this what you want.

**Comment by saltedcoffii** [comment]
That's perfect, thank you so much!!
